from langchain_core.messages import BaseMessage
from typing import Sequence, TypedDict
from pydantic import BaseModel, Field

class State(TypedDict):
    """TypedDict for the entire state structure."""
    messages: Sequence[BaseMessage]

    sender: str = ""

    # Path to the input data
    datapath: str = ""
    
    eda_report: str = ""
    statistic_report: str = ""
    cluster_report: str = ""
    visualization_report: str = ""
    hypothesis_report: str = ""
    reasoning_report: str = ""
    total_summary_report: str = ""
    final_report: str = ""


class NoteState(BaseModel):
    """Pydantic model for the entire state structure, used by the NoteTaker agent."""
    messages: Sequence[BaseMessage] = Field(default_factory=list, description="List of message dictionaries")
    
    datapath: str = Field(default="", description="Path to the input data file")
    
    eda_report: str = Field(default="", description="The summary report from the Data Explorer Agent")
    statistic_report: str = Field(default="", description="The summary report from the Data Statistic Agent")
    cluster_report: str = Field(default="", description="The summary report from the Data Cluster Agent")
    visualization_report: str = Field(default="", description="The summary report from the Data Visualization Agent")
    hypothesis_report: str = Field(default="", description="The questions generated by the Hypothesis Generator Agent")
    reasoning_report: str = Field(default="", description="The answers provided by the Reasoner Agent")
    total_summary_report: str = Field(default="", description="The comprehensive summary from the Quality Review Agent")
    final_report: str = Field(default="", description="The final insights report from the Synthesis Agent")

    class Config:
        arbitrary_types_allowed = True